 {

            "pretrained_model_name_or_path": "runwayml/stable-diffusion-v1-5",
            "resolution": 512,
            "train_batch_size": 1,
            "max_train_steps": 10000,
            "checkpointing_steps": 5000,
            "checkpoints_total_limit": null,
            "gradient_accumulation_steps": 1,
            "trained_model_path": "/home/ubuntu/Yasamani/multi_sd_results/crack",
            "adam_beta1": 0.9,
            "adam_beta2": 0.999,
            "adam_weight_decay": 0.01,
            "adam_epsilon": 0.00000001,
            "max_grad_norm": 1.0,
            "learning_rate": 0.000005,
            "scale_lr": false,
            "lr_scheduler": "constant",
            "lr_warmup_steps": 500,
            "lr_num_cycles": 1,
            "lr_power": 1.0,
            "logging_dir": "logs",
            "report_to": "tensorboard",
            "num_train_epochs": 1,
            "with_prior_preservation": false,
            "prior_loss_weight": 1.0,
            "num_class_images": 1,
            "center_crop": false,
            "sample_batch_size": 6,
            
            "allow_tf32": null,
            "mixed_precision": "fp16",
            "enable_xformers_memory_efficient_attention": null,
            "push_to_hub": null,
            "hub_token": null,
            "hub_model_id": null,
            "revision": null,
            "tokenizer_name": null,
            "instance_data_dir": "/home/ubuntu/Yasamani/dataset/multi_subject_SD_datasets/crack",
            "class_data_dir": null,
            "instance_prompt": "a photo of a ##Crack@mtl## defect metal",
            "class_prompt": null,
            "checkpoint_path": "/home/ubuntu/Yasamani/multi_sd_results/crack.ckpt",
            "seed": null,
            "train_text_encoder": null,
            "resume_from_checkpoint": null,
            "use_8bit_adam": true,
            "gradient_checkpointing": null,
            "prior_generation_precision": null,
            "local_rank": -1,
            "half": true,
            "use_safetensors": null
}
